all:
  children:
    # --------------------------------------------
    # for local VMs so no need for proxy 
    # --------------------------------------------
    local:
      hosts:
        orb:
          ansible_host: orb@orb
          ansible_user: gavin
      vars:
        ansible_ssh_common_args: ''

    # --------------------------------------------
    # for VMs on my proxmox hardware - proxy through root
    # --------------------------------------------
    pve:
      hosts:
        # pi-hole:
        #   ansible_host: 10.0.0.53
      vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: '-o ProxyJump=root@{{ proxmox_host }}'

    # --------------------------------------------
    # for cloud VMs like aws or gcp
    # --------------------------------------------
    cloud:
      hosts:
        # example-cloud-vm:
        #   ansible_host: 1.2.3.4
      vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: ''
